export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';

export const SEND_MESSAGE_REMOTE_SUCCESS = 'SEND_MESSAGE_REMOTE_SUCCESS';
export const SEND_MESSAGE_CLIENT_SUCCESS = 'SEND_MESSAGE_CLIENT_SUCCESS';
